/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'DataToRadioMsg'
 * message type.
 */

public class DataToRadioMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 10;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 7;

    /** Create a new DataToRadioMsg of size 10. */
    public DataToRadioMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new DataToRadioMsg of the given data_length. */
    public DataToRadioMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new DataToRadioMsg with the given data_length
     * and base offset.
     */
    public DataToRadioMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new DataToRadioMsg using the given byte array
     * as backing store.
     */
    public DataToRadioMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new DataToRadioMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public DataToRadioMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new DataToRadioMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public DataToRadioMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new DataToRadioMsg embedded in the given message
     * at the given base offset.
     */
    public DataToRadioMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new DataToRadioMsg embedded in the given message
     * at the given base offset and length.
     */
    public DataToRadioMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <DataToRadioMsg> \n";
      try {
        s += "  [id=0x"+Long.toHexString(get_id())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [resend1to2=0x"+Long.toHexString(get_resend1to2())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [resend2to3=0x"+Long.toHexString(get_resend2to3())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [buffer=0x"+Long.toHexString(get_buffer())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [data=0x"+Long.toHexString(get_data())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: id
    //   Field type: int, unsigned
    //   Offset (bits): 0
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'id' is signed (false).
     */
    public static boolean isSigned_id() {
        return false;
    }

    /**
     * Return whether the field 'id' is an array (false).
     */
    public static boolean isArray_id() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'id'
     */
    public static int offset_id() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'id'
     */
    public static int offsetBits_id() {
        return 0;
    }

    /**
     * Return the value (as a int) of the field 'id'
     */
    public int get_id() {
        return (int)getUIntBEElement(offsetBits_id(), 16);
    }

    /**
     * Set the value of the field 'id'
     */
    public void set_id(int value) {
        setUIntBEElement(offsetBits_id(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'id'
     */
    public static int size_id() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'id'
     */
    public static int sizeBits_id() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: resend1to2
    //   Field type: int, unsigned
    //   Offset (bits): 16
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'resend1to2' is signed (false).
     */
    public static boolean isSigned_resend1to2() {
        return false;
    }

    /**
     * Return whether the field 'resend1to2' is an array (false).
     */
    public static boolean isArray_resend1to2() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'resend1to2'
     */
    public static int offset_resend1to2() {
        return (16 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'resend1to2'
     */
    public static int offsetBits_resend1to2() {
        return 16;
    }

    /**
     * Return the value (as a int) of the field 'resend1to2'
     */
    public int get_resend1to2() {
        return (int)getUIntBEElement(offsetBits_resend1to2(), 16);
    }

    /**
     * Set the value of the field 'resend1to2'
     */
    public void set_resend1to2(int value) {
        setUIntBEElement(offsetBits_resend1to2(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'resend1to2'
     */
    public static int size_resend1to2() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'resend1to2'
     */
    public static int sizeBits_resend1to2() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: resend2to3
    //   Field type: int, unsigned
    //   Offset (bits): 32
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'resend2to3' is signed (false).
     */
    public static boolean isSigned_resend2to3() {
        return false;
    }

    /**
     * Return whether the field 'resend2to3' is an array (false).
     */
    public static boolean isArray_resend2to3() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'resend2to3'
     */
    public static int offset_resend2to3() {
        return (32 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'resend2to3'
     */
    public static int offsetBits_resend2to3() {
        return 32;
    }

    /**
     * Return the value (as a int) of the field 'resend2to3'
     */
    public int get_resend2to3() {
        return (int)getUIntBEElement(offsetBits_resend2to3(), 16);
    }

    /**
     * Set the value of the field 'resend2to3'
     */
    public void set_resend2to3(int value) {
        setUIntBEElement(offsetBits_resend2to3(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'resend2to3'
     */
    public static int size_resend2to3() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'resend2to3'
     */
    public static int sizeBits_resend2to3() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: buffer
    //   Field type: int, unsigned
    //   Offset (bits): 48
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'buffer' is signed (false).
     */
    public static boolean isSigned_buffer() {
        return false;
    }

    /**
     * Return whether the field 'buffer' is an array (false).
     */
    public static boolean isArray_buffer() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'buffer'
     */
    public static int offset_buffer() {
        return (48 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'buffer'
     */
    public static int offsetBits_buffer() {
        return 48;
    }

    /**
     * Return the value (as a int) of the field 'buffer'
     */
    public int get_buffer() {
        return (int)getUIntBEElement(offsetBits_buffer(), 16);
    }

    /**
     * Set the value of the field 'buffer'
     */
    public void set_buffer(int value) {
        setUIntBEElement(offsetBits_buffer(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'buffer'
     */
    public static int size_buffer() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'buffer'
     */
    public static int sizeBits_buffer() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: data
    //   Field type: int, unsigned
    //   Offset (bits): 64
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'data' is signed (false).
     */
    public static boolean isSigned_data() {
        return false;
    }

    /**
     * Return whether the field 'data' is an array (false).
     */
    public static boolean isArray_data() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'data'
     */
    public static int offset_data() {
        return (64 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'data'
     */
    public static int offsetBits_data() {
        return 64;
    }

    /**
     * Return the value (as a int) of the field 'data'
     */
    public int get_data() {
        return (int)getUIntBEElement(offsetBits_data(), 16);
    }

    /**
     * Set the value of the field 'data'
     */
    public void set_data(int value) {
        setUIntBEElement(offsetBits_data(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'data'
     */
    public static int size_data() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'data'
     */
    public static int sizeBits_data() {
        return 16;
    }

}
